name: chs_connect
description: Social App for Cenfex High School

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  shared_preferences: ^0.5.2+1
  page_transition: ^1.1.0
  firebase_auth: ^0.11.1
  cloud_firestore: ^0.11.0+2
  firebase_storage: ^3.0.0
  firebase_messaging: ^5.0.1+1
  firebase_analytics: ^3.0.1
  firebase_crashlytics: ^0.0.4+3
  google_sign_in: ^4.0.1+3
  rxdart: ^0.18.1
  rebloc: ^0.2.1
  http: ^0.12.0+2
  equatable: ^0.2.5
  wave: ^0.0.8
  flutter_spinkit: ^3.1.0
  community_material_icon: ^3.5.95
  image_picker: ^0.6.0+8
  intl: ^0.15.8
  get_version: ^0.1.0
  dynamic_theme: ^1.0.1
  version: ^1.0.3
  timeago: ^2.0.16
  flushbar: ^1.5.3
  bubble_bottom_bar: ^1.2.0
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
  assets:
    - assets/images/logo/
    - assets/images/icons/
  fonts:
    - family: Work Sans
      fonts:
        - asset: assets/fonts/worksans/WorkSans-Light.ttf
          weight: 100
        - asset: assets/fonts/worksans/WorkSans-Bold.ttf
          weight: 300
        - asset: assets/fonts/worksans/WorkSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/worksans/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/worksans/WorkSans-SemiBold.ttf
          weight: 600

    - family: Rochester
      fonts:
        - asset: assets/fonts/Rochester-Regular.ttf

    - family: Icons
      fonts:
        - asset: assets/fonts/icons.ttf