name: chs_connect
description: Social App for Cenfex High School
version: 1.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  shared_preferences: ^0.5.2+1
  permission_handler: ^3.1.0
  google_maps_flutter: ^0.5.19
  location: ^2.3.5
  firebase_auth: ^0.11.1+7
  cloud_firestore: ^0.12.5+2
  firebase_storage: ^3.0.2
  firebase_messaging: ^5.0.4
  firebase_analytics: ^3.0.3
  firebase_crashlytics: ^0.0.4+8
  firebase_dynamic_links: ^0.4.0+4
  google_sign_in: ^4.0.2
  rxdart: ^0.18.1
  http: ^0.12.0+2
  country_pickers: ^1.1.0
  flutter_statusbar_manager : ^1.0.2
  wave: ^0.0.8
  flutter_lottie: ^0.2.0
  flutter_spinkit: ^3.1.0
  community_material_icon: ^3.5.95
  datetime_picker_formfield: ^0.2.0
  multi_image_picker: ^4.3.4
  image_cropper: ^1.0.2
  flutter_image_compress: ^0.6.0
  extended_image: ^0.5.1
  uuid: ^2.0.2
  path_provider: ^1.1.0
  get_version: ^0.1.0
  version: ^1.0.3
  timeago: ^2.0.16
  flushbar: ^1.5.3
  flutter_colorpicker: ^0.2.5
  provider: ^2.0.1+1
  localstorage: ^2.0.0
  flutter_mobx: ^0.2.1+2
  bubble_bottom_bar: ^1.2.0
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dependency_overrides:
#  path_provider: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo/
    - assets/images/icons/
    - assets/images/drawables/
    - assets/animations/

  fonts:
    - family: Work Sans
      fonts:
        - asset: assets/fonts/worksans/WorkSans-Light.ttf
          weight: 100
        - asset: assets/fonts/worksans/WorkSans-Bold.ttf
          weight: 300
        - asset: assets/fonts/worksans/WorkSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/worksans/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/worksans/WorkSans-SemiBold.ttf
          weight: 600

    - family: Rochester
      fonts:
        - asset: assets/fonts/Rochester-Regular.ttf

    - family: Icons
      fonts:
        - asset: assets/fonts/icons.ttf